version: '3.4'
services:
  stripe:
    image: homeless-stripe
    container_name: homeless-stripe
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/homeless_stripe
    ports:
      - "8080:8080"
    networks:
      - homeless-network

networks:
  homeless-network:
    external: true